name: Build

on:
  push:
    paths:
      - '.github/workflows/build.yml'
      - 'src-tauri/**/*'
      - 'src/**/*'
  pull_request:
    paths:
      - '.github/workflows/build.yml'
      - 'src-tauri/**/*'
      - 'src/**/*'

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:
  build-win:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: Install deps and build
        run: yarn && yarn tauri build

      - name: Compress build
        uses: vimtor/action-zip@v1
        with:
          files: src-tauri/target/release/lang/ src-tauri/target/release/keys/ src-tauri/target/release/patch/ src-tauri/target/release/Cultivation.exe src-tauri/target/release/bundle/msi/
          recursive: true
          dest: Cultivation.zip

      - name: Upload build
        uses: actions/upload-artifact@v4
        with:
          name: CultivationWin
          path: Cultivation.zip
  build-ubuntu:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: Install libraries
        run: |
          sudo apt update
          sudo apt install libwebkit2gtk-4.1-dev \
            build-essential \
            curl \
            wget \
            file \
            libxdo-dev \
            libssl-dev \
            libayatana-appindicator3-dev \
            librsvg2-dev \
            protobuf-compiler \
            libprotobuf-dev

      - name: Install deps and build release
        run: yarn && NO_STRIP=true yarn tauri build

      - name: Compress build
        uses: vimtor/action-zip@v1
        with:
          files: src-tauri/target/release/lang/ src-tauri/target/release/keys/ src-tauri/target/release/patch/ src-tauri/target/release/cultivation src-tauri/target/release/bundle/
          recursive: true
          dest: Cultivation.zip

      - name: Upload build
        uses: actions/upload-artifact@v4
        with:
          name: CultivationLinux
          path: Cultivation.zip
